// Every user-facing string lives here (section 5: pt-BR and en at minimum).
const ptBR = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Protótipo de tiro · Fase 1',
  play: 'JOGAR',
  resume: 'VOLTAR AO JOGO',
  clickToResume: 'Clique para voltar ao jogo',
  loading: 'Carregando',
  controls: 'Controles',
  settings: 'Configurações',
  sensitivity: 'Sensibilidade',
  adsSensitivity: 'Sensibilidade na mira',
  fov: 'Campo de visão',
  volume: 'Volume',
  invertY: 'Inverter eixo Y',
  health: 'VIDA',
  reload: 'RECARREGUE',
  noAmmo: 'SEM MUNIÇÃO',
  reloading: 'RECARREGANDO…',
  points: 'Pontos',
  kills: 'Abates',
  accuracy: 'Precisão',
  you: 'Você',
  kill: 'Abate',
  headshot: 'Tiro na cabeça',
  longShot: 'Longa distância',
  respawnIn: 'Renascendo em {s}…',
  debugHint: 'F3 depuração · F4 hitboxes',
  keyMove: 'Mover',
  keyJump: 'Pular',
  keyCrouch: 'Agachar (correndo: derrapar)',
  keySprint: 'Correr',
  keyFire: 'Atirar',
  keyAds: 'Mirar',
  keyReload: 'Recarregar',
  keyPause: 'Menu',
  mouseLeft: 'Botão esq.',
  mouseRight: 'Botão dir.',
  keyMelee: 'Facada',
  keyTaunt: 'Humilhar (perto do corpo)',
  keyGrenade: 'Granada (segure para cozinhar)',
  grenadeName: 'Granada',
  knife: 'Facada',
  knifeName: 'Faca',
  weaponRifle: 'Rifle',
  weaponKnife: 'Faca',
  weaponGrenade: 'Granada',
  levelUp: '{weapon} nível {level}',
  mineLimit: 'Máximo de {n} minas no mapa',
  arsenal: 'Arsenal',
  arsenalHint: 'Cada abate evolui só a arma que matou. Clique num nível liberado para equipar.',
  level: 'Nível',
  equipped: 'Equipado',
  equip: 'Equipar',
  locked: 'Bloqueado',
  xpToNext: '{xp} / {next} pontos para o nível {level}',
  maxLevel: 'Nível máximo! {xp} pontos',
  unlockAt: 'Libera com {xp} pontos',
  dogBite: 'Mordida',
  backstab: 'Pelas costas',
  groin: 'No pássaro',
  groinBanner: 'NO PÁSSARO!',
  humiliation: 'Humilhação',
  humiliatedBanner: 'HUMILHADO!',
  danceName: 'Dancinha da Vitória',
  promptTaunt: 'Humilhar {name}',
  dancing: 'Humilhando {name}…',
  quality: 'Qualidade gráfica',
  qualityAuto: 'Automática',
  qualityLow: 'Baixa',
  qualityMedium: 'Média',
  qualityHigh: 'Alta',
  yourName: 'Seu nome',
  sexLabel: 'Sexo',
  sexMale: '♂ Masculino',
  sexFemale: '♀ Feminino',
  playOnline: 'JOGAR ONLINE',
  playOffline: 'Campo de tiro (bonecos parados)',
  playBots: 'CONTRA BOTS',
  botSkill: 'Dificuldade',
  botCount: 'Bots',
  skillEasy: 'Fácil',
  skillNormal: 'Normal',
  skillHard: 'Difícil',
  botsSubtitle: 'Contra {n} bots · mata-mata livre',
  sessions: 'Sessões',
  createSession: 'CRIAR',
  sessionNamePlaceholder: 'Nome da nova sessão',
  back: 'Voltar',
  noSessions: 'Nenhuma sessão aberta. Crie a primeira!',
  join: 'ENTRAR',
  full: 'LOTADA',
  joining: 'Entrando…',
  connecting: 'Conectando ao servidor…',
  connectedAs: 'Conectado como {name}.',
  disconnected: 'Conexão com o servidor perdida.',
  serverOffline: 'Servidor fora do ar. Rode "npm run server" (ou jogue o treino offline).',
  needName: 'Escolha um nome primeiro.',
  exitToHome: 'Sair para o início',
  scoreboard: 'Placar',
  player: 'Jogador',
  deaths: 'Mortes',
  humiliationsShort: 'Humilh.',
  killedBy: '{name} te eliminou',
  killedByWith: '{name} te eliminou com {weapon}',
  playerJoined: '{name} entrou',
  playerLeft: '{name} saiu',
  lostConnection: 'Sem conexão com o servidor',
  accountGuest: 'Sem conta: treino e bots estão liberados. Para jogar online, entre ou crie uma conta.',
  signIn: 'ENTRAR',
  signUp: 'CRIAR CONTA',
  profile: 'PERFIL',
  signOut: 'Sair da conta',
  email: 'E-mail',
  password: 'Senha',
  gameName: 'Nome no jogo',
  signInTitle: 'Entrar',
  signUpTitle: 'Criar conta',
  forgotTitle: 'Esqueci a senha',
  resetTitle: 'Nova senha',
  chooseNameTitle: 'Escolha seu nome no jogo',
  withDiscord: 'Entrar com Discord',
  forgotLink: 'Esqueci a senha',
  haveAccount: 'Já tenho conta',
  noAccount: 'Criar uma conta',
  send: 'ENVIAR',
  save: 'SALVAR',
  resetSent: 'Se esse e-mail tiver conta, enviamos um link válido por 24 horas.',
  resetDone: 'Senha trocada. Entre com a senha nova.',
  needAccount: 'Entre na sua conta para jogar online.',
  passwordHint: 'De 8 a 128 caracteres.',
  nameHint: 'De 3 a 16 letras ou números. Aparece como Nome#1234.',
  levelShort: 'Nv {level}',
  accountLevelUp: '🏅 Conta nível {level}!',
  sessionEnded: 'Sua sessão foi encerrada (saída da conta, troca de senha, exclusão ou suspensão).',
  connectedElsewhere: 'Sua conta entrou no jogo em outro lugar.',
  profileTitle: 'Perfil',
  statsTitle: 'Estatísticas',
  recentTitle: 'Últimas participações',
  noParticipations: 'Nenhuma partida online ainda.',
  statKills: 'Abates',
  statDeaths: 'Mortes',
  statHead: 'Na cabeça',
  statGroin: 'No pássaro',
  statKnife: 'Facadas',
  statBackstab: 'Pelas costas',
  statGrenade: 'Com granada',
  statHumiliations: 'Humilhações',
  statTime: 'Tempo jogado',
  statMatches: 'Participações',
  customize: 'PERSONALIZAR PERSONAGEM',
  changeName: 'Trocar nome',
  nameFreeAt: 'Próxima troca liberada em {date}.',
  nameRule: 'A primeira troca é livre; depois, uma a cada 7 dias.',
  linkDiscord: 'Vincular Discord',
  unlinkDiscord: 'Desvincular Discord',
  discordLinked: 'Discord vinculado.',
  deleteAccount: 'Excluir conta',
  deleteConfirm: 'Excluir a conta? Você tem 30 dias para desistir entrando de novo. Depois disso, nome e e-mail são apagados.',
  cancelDeletion: 'Cancelar exclusão',
  deletionPending: 'Conta marcada para exclusão em {date}. O jogo online fica bloqueado até você cancelar.',
  saved: 'Salvo.',
  errCredentials: 'E-mail ou senha incorretos.',
  errTooMany: 'Muitas tentativas. Espere um minuto e tente de novo.',
  errSuspended: 'Esta conta está suspensa.',
  errPendingDeletion: 'Esta conta está marcada para exclusão. Cancele no Perfil para jogar online.',
  errEmailUsed: 'Esse e-mail já tem conta. Entre ou use "Esqueci a senha".',
  errEmailInvalid: 'E-mail inválido.',
  errPasswordInvalid: 'A senha precisa ter de 8 a 128 caracteres.',
  errNameInvalid: 'Nome inválido: de 3 a 16 letras ou números.',
  errNameTaken: 'Esse nome não tem mais números livres. Tente outro.',
  errNameCooldown: 'Você só pode trocar de nome de novo em {date}.',
  errTokenInvalid: 'Link inválido ou vencido. Peça outro em "Esqueci a senha".',
  errOnlyLogin: 'O Discord é a única forma de entrar nesta conta.',
  errDiscordUnavailable: 'Entrar com Discord não está disponível neste endereço.',
  errDiscordLinked: 'Esse Discord já está vinculado a uma conta.',
  errUnauthorized: 'Entre na sua conta de novo.',
  errOffline: 'Servidor fora do ar. Rode "npm run dev:online" (ou jogue o treino offline).',
  errGeneric: 'Algo deu errado. Tente de novo.',
  onlineSubtitle: 'Sessão: {name} · mata-mata livre',
  gpuWarning:
    'Seu navegador está desenhando o jogo sem placa de vídeo (renderizador: {gpu}), por isso fica em ~10 FPS. Ative “Usar aceleração gráfica quando disponível” em chrome://settings/system (no Edge: edge://settings/system) e reinicie o navegador.',
} as const;

const en: Record<keyof typeof ptBR, string> = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Shooting prototype · Phase 1',
  play: 'PLAY',
  resume: 'BACK TO THE GAME',
  clickToResume: 'Click to return to the game',
  loading: 'Loading',
  controls: 'Controls',
  settings: 'Settings',
  sensitivity: 'Sensitivity',
  adsSensitivity: 'ADS sensitivity',
  fov: 'Field of view',
  volume: 'Volume',
  invertY: 'Invert Y axis',
  health: 'HEALTH',
  reload: 'RELOAD',
  noAmmo: 'NO AMMO',
  reloading: 'RELOADING…',
  points: 'Points',
  kills: 'Kills',
  accuracy: 'Accuracy',
  you: 'You',
  kill: 'Kill',
  headshot: 'Headshot',
  longShot: 'Long shot',
  respawnIn: 'Respawning in {s}…',
  debugHint: 'F3 debug · F4 hitboxes',
  keyMove: 'Move',
  keyJump: 'Jump',
  keyCrouch: 'Crouch (while sprinting: slide)',
  keySprint: 'Sprint',
  keyFire: 'Fire',
  keyAds: 'Aim',
  keyReload: 'Reload',
  keyPause: 'Menu',
  mouseLeft: 'Left mouse',
  mouseRight: 'Right mouse',
  keyMelee: 'Knife',
  keyTaunt: 'Humiliate (near a body)',
  keyGrenade: 'Grenade (hold to cook)',
  grenadeName: 'Grenade',
  knife: 'Knifed',
  knifeName: 'Knife',
  weaponRifle: 'Rifle',
  weaponKnife: 'Knife',
  weaponGrenade: 'Grenade',
  levelUp: '{weapon} level {level}',
  mineLimit: 'At most {n} mines on the map',
  arsenal: 'Arsenal',
  arsenalHint: 'Each kill levels up only the weapon that made it. Click an unlocked level to equip it.',
  level: 'Level',
  equipped: 'Equipped',
  equip: 'Equip',
  locked: 'Locked',
  xpToNext: '{xp} / {next} points to level {level}',
  maxLevel: 'Max level! {xp} points',
  unlockAt: 'Unlocks at {xp} points',
  dogBite: 'Bite',
  backstab: 'Backstab',
  groin: 'Right in the birdie',
  groinBanner: 'RIGHT IN THE BIRDIE!',
  humiliation: 'Humiliation',
  humiliatedBanner: 'HUMILIATED!',
  danceName: 'Victory Dance',
  promptTaunt: 'Humiliate {name}',
  dancing: 'Humiliating {name}…',
  quality: 'Graphics quality',
  qualityAuto: 'Automatic',
  qualityLow: 'Low',
  qualityMedium: 'Medium',
  qualityHigh: 'High',
  yourName: 'Your name',
  sexLabel: 'Sex',
  sexMale: '♂ Male',
  sexFemale: '♀ Female',
  playOnline: 'PLAY ONLINE',
  playOffline: 'Shooting range (static dummies)',
  playBots: 'VS BOTS',
  botSkill: 'Difficulty',
  botCount: 'Bots',
  skillEasy: 'Easy',
  skillNormal: 'Normal',
  skillHard: 'Hard',
  botsSubtitle: 'Against {n} bots · free-for-all',
  sessions: 'Sessions',
  createSession: 'CREATE',
  sessionNamePlaceholder: 'New session name',
  back: 'Back',
  noSessions: 'No open sessions. Create the first one!',
  join: 'JOIN',
  full: 'FULL',
  joining: 'Joining…',
  connecting: 'Connecting to the server…',
  connectedAs: 'Connected as {name}.',
  disconnected: 'Lost connection to the server.',
  serverOffline: 'Server is down. Run "npm run server" (or play offline training).',
  needName: 'Pick a name first.',
  exitToHome: 'Back to home',
  scoreboard: 'Scoreboard',
  player: 'Player',
  deaths: 'Deaths',
  humiliationsShort: 'Humil.',
  killedBy: '{name} took you out',
  killedByWith: '{name} took you out with {weapon}',
  playerJoined: '{name} joined',
  playerLeft: '{name} left',
  lostConnection: 'No connection to the server',
  accountGuest: 'No account: training and bots are open. To play online, sign in or create an account.',
  signIn: 'SIGN IN',
  signUp: 'SIGN UP',
  profile: 'PROFILE',
  signOut: 'Sign out',
  email: 'E-mail',
  password: 'Password',
  gameName: 'In-game name',
  signInTitle: 'Sign in',
  signUpTitle: 'Create account',
  forgotTitle: 'Forgot password',
  resetTitle: 'New password',
  chooseNameTitle: 'Choose your in-game name',
  withDiscord: 'Sign in with Discord',
  forgotLink: 'Forgot password',
  haveAccount: 'I have an account',
  noAccount: 'Create an account',
  send: 'SEND',
  save: 'SAVE',
  resetSent: 'If that e-mail has an account, we sent a link valid for 24 hours.',
  resetDone: 'Password changed. Sign in with the new one.',
  needAccount: 'Sign in to play online.',
  passwordHint: '8 to 128 characters.',
  nameHint: '3 to 16 letters or numbers. Shown as Name#1234.',
  levelShort: 'Lv {level}',
  accountLevelUp: '🏅 Account level {level}!',
  sessionEnded: 'Your session ended (sign-out, password change, deletion or suspension).',
  connectedElsewhere: 'Your account joined the game somewhere else.',
  profileTitle: 'Profile',
  statsTitle: 'Stats',
  recentTitle: 'Recent sessions',
  noParticipations: 'No online matches yet.',
  statKills: 'Kills',
  statDeaths: 'Deaths',
  statHead: 'Headshots',
  statGroin: 'Below the belt',
  statKnife: 'Knife kills',
  statBackstab: 'Backstabs',
  statGrenade: 'Grenade kills',
  statHumiliations: 'Humiliations',
  statTime: 'Time played',
  statMatches: 'Sessions',
  customize: 'CUSTOMIZE CHARACTER',
  changeName: 'Change name',
  nameFreeAt: 'Next change available on {date}.',
  nameRule: 'The first change is free; then one every 7 days.',
  linkDiscord: 'Link Discord',
  unlinkDiscord: 'Unlink Discord',
  discordLinked: 'Discord linked.',
  deleteAccount: 'Delete account',
  deleteConfirm: 'Delete the account? You have 30 days to change your mind by signing in again. After that, name and e-mail are erased.',
  cancelDeletion: 'Cancel deletion',
  deletionPending: 'Account scheduled for deletion on {date}. Online play is blocked until you cancel.',
  saved: 'Saved.',
  errCredentials: 'Wrong e-mail or password.',
  errTooMany: 'Too many attempts. Wait a minute and try again.',
  errSuspended: 'This account is suspended.',
  errPendingDeletion: 'This account is scheduled for deletion. Cancel it in Profile to play online.',
  errEmailUsed: 'That e-mail already has an account. Sign in or use "Forgot password".',
  errEmailInvalid: 'Invalid e-mail.',
  errPasswordInvalid: 'The password needs 8 to 128 characters.',
  errNameInvalid: 'Invalid name: 3 to 16 letters or numbers.',
  errNameTaken: 'That name has no free numbers left. Try another.',
  errNameCooldown: 'You can change your name again on {date}.',
  errTokenInvalid: 'Invalid or expired link. Ask for another in "Forgot password".',
  errOnlyLogin: 'Discord is the only way into this account.',
  errDiscordUnavailable: 'Discord sign-in is not available at this address.',
  errDiscordLinked: 'That Discord is already linked to an account.',
  errUnauthorized: 'Please sign in again.',
  errOffline: 'Server is down. Run "npm run dev:online" (or play offline training).',
  errGeneric: 'Something went wrong. Try again.',
  onlineSubtitle: 'Session: {name} · free-for-all',
  gpuWarning:
    'Your browser is rendering the game without a graphics card (renderer: {gpu}), which caps it around 10 FPS. Enable “Use graphics acceleration when available” in chrome://settings/system (Edge: edge://settings/system) and restart the browser.',
};

export const TIPS = {
  'pt-BR': [
    'Dica: atirar no inimigo costuma funcionar melhor que atirar na parede.',
    'Dica: o boneco não revida. Ainda.',
    'Dica: cair de 7 metros dói. Pergunte ao seu joelho.',
    'Dica: mirar na cabeça dá o dobro de dano e o triplo de arrogância.',
    'Dica: correr e atirar ao mesmo tempo não é permitido. Sindicato dos braços.',
    'Dica: o caminhão de sorvete não vende sorvete. Mas toca música.',
    'Dica: os flamingos não têm culpa de nada.',
  ],
  en: [
    'Tip: shooting the enemy usually works better than shooting the wall.',
    "Tip: the dummy doesn't shoot back. Yet.",
    'Tip: falling 7 meters hurts. Ask your knees.',
    'Tip: headshots deal double damage and triple arrogance.',
    'Tip: no shooting while sprinting. Arm union rules.',
    "Tip: the ice cream truck doesn't sell ice cream. It does play music.",
    'Tip: the flamingos are innocent.',
  ],
};

export const DEATH_MESSAGES = {
  'pt-BR': {
    fall: ['Você venceu a gravidade. Brincadeira, ela venceu.', 'Da próxima vez, tente cair de pé.', 'A calçada mandou lembranças.'],
    void: ['Você saiu do mapa. O mapa não sentiu sua falta.', 'Explorador corajoso. Explorador morto.'],
    explosion: ['Você cozinhou demais. A granada, e você.', 'Dica: a granada vai na direção do inimigo.'],
    dog: ['A Amora não gostou da visita.', 'Mordido pela Amora. Fofa, mas brava.', 'Quintal errado. Au.'],
  },
  en: {
    fall: ['You beat gravity. Just kidding, it beat you.', 'Next time, try landing on your feet.', 'The sidewalk says hi.'],
    void: ["You left the map. The map didn't miss you.", 'Brave explorer. Dead explorer.'],
    explosion: ['You overcooked it. The grenade, and yourself.', 'Tip: the grenade goes toward the enemy.'],
    dog: ['Amora did not like your visit.', 'Bitten by Amora. Fluffy, but grumpy.', 'Wrong yard. Woof.'],
  },
};

export type Lang = 'pt-BR' | 'en';
export type StringKey = keyof typeof ptBR;

let lang: Lang = navigator.language?.toLowerCase().startsWith('pt') ? 'pt-BR' : 'en';
const dicts: Record<Lang, Record<StringKey, string>> = { 'pt-BR': ptBR, en };

export function getLang(): Lang {
  return lang;
}

export function setLang(l: Lang) {
  lang = l;
}

export function t(key: StringKey, params: Record<string, string | number> = {}): string {
  return dicts[lang][key].replace(/\{(\w+)\}/g, (_, k) => String(params[k] ?? ''));
}

export function pick<T>(list: T[]): T {
  return list[(Math.random() * list.length) | 0];
}
