// Every user-facing string lives here (section 5: pt-BR and en at minimum).
const ptBR = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Protótipo de tiro · Fase 1',
  play: 'JOGAR',
  resume: 'VOLTAR AO JOGO',
  clickToResume: 'Clique para voltar ao jogo',
  loading: 'Carregando',
  controls: 'Controles',
  settings: 'Configurações',
  sensitivity: 'Sensibilidade',
  adsSensitivity: 'Sensibilidade na mira',
  fov: 'Campo de visão',
  volume: 'Volume',
  invertY: 'Inverter eixo Y',
  health: 'VIDA',
  reload: 'RECARREGUE',
  noAmmo: 'SEM MUNIÇÃO',
  reloading: 'RECARREGANDO…',
  points: 'Pontos',
  kills: 'Abates',
  accuracy: 'Precisão',
  you: 'Você',
  kill: 'Abate',
  headshot: 'Tiro na cabeça',
  longShot: 'Longa distância',
  respawnIn: 'Renascendo em {s}…',
  debugHint: 'F3 depuração · F4 hitboxes',
  keyMove: 'Mover',
  keyJump: 'Pular',
  keyCrouch: 'Agachar (correndo: derrapar)',
  keySprint: 'Correr',
  keyFire: 'Atirar',
  keyAds: 'Mirar',
  keyReload: 'Recarregar',
  keyPause: 'Menu',
  mouseLeft: 'Botão esq.',
  mouseRight: 'Botão dir.',
  keyMelee: 'Facada',
  keyTaunt: 'Humilhar (perto do corpo)',
  keyGrenade: 'Granada (segure para cozinhar)',
  grenadeName: 'Granada',
  knife: 'Facada',
  knifeName: 'Faca',
  dogBite: 'Mordida',
  backstab: 'Pelas costas',
  groin: 'No pássaro',
  groinBanner: 'NO PÁSSARO!',
  humiliation: 'Humilhação',
  humiliatedBanner: 'HUMILHADO!',
  danceName: 'Dancinha da Vitória',
  promptTaunt: 'Humilhar {name}',
  dancing: 'Humilhando {name}…',
  quality: 'Qualidade gráfica',
  qualityAuto: 'Automática',
  qualityLow: 'Baixa',
  qualityMedium: 'Média',
  qualityHigh: 'Alta',
  yourName: 'Seu nome',
  sexLabel: 'Sexo',
  sexMale: '♂ Masculino',
  sexFemale: '♀ Feminino',
  playOnline: 'JOGAR ONLINE',
  playOffline: 'Campo de tiro (bonecos parados)',
  playBots: 'CONTRA BOTS',
  botSkill: 'Dificuldade',
  botCount: 'Bots',
  skillEasy: 'Fácil',
  skillNormal: 'Normal',
  skillHard: 'Difícil',
  botsSubtitle: 'Contra {n} bots · mata-mata livre',
  sessions: 'Sessões',
  createSession: 'CRIAR',
  sessionNamePlaceholder: 'Nome da nova sessão',
  back: 'Voltar',
  noSessions: 'Nenhuma sessão aberta. Crie a primeira!',
  join: 'ENTRAR',
  full: 'LOTADA',
  joining: 'Entrando…',
  connecting: 'Conectando ao servidor…',
  connectedAs: 'Conectado como {name}.',
  disconnected: 'Conexão com o servidor perdida.',
  serverOffline: 'Servidor fora do ar. Rode "npm run server" (ou jogue o treino offline).',
  needName: 'Escolha um nome primeiro.',
  exitToHome: 'Sair para o início',
  scoreboard: 'Placar',
  player: 'Jogador',
  deaths: 'Mortes',
  humiliationsShort: 'Humilh.',
  killedBy: '{name} te eliminou',
  killedByWith: '{name} te eliminou com {weapon}',
  playerJoined: '{name} entrou',
  playerLeft: '{name} saiu',
  lostConnection: 'Sem conexão com o servidor',
  onlineSubtitle: 'Sessão: {name} · mata-mata livre',
  gpuWarning:
    'Seu navegador está desenhando o jogo sem placa de vídeo (renderizador: {gpu}), por isso fica em ~10 FPS. Ative “Usar aceleração gráfica quando disponível” em chrome://settings/system (no Edge: edge://settings/system) e reinicie o navegador.',
} as const;

const en: Record<keyof typeof ptBR, string> = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Shooting prototype · Phase 1',
  play: 'PLAY',
  resume: 'BACK TO THE GAME',
  clickToResume: 'Click to return to the game',
  loading: 'Loading',
  controls: 'Controls',
  settings: 'Settings',
  sensitivity: 'Sensitivity',
  adsSensitivity: 'ADS sensitivity',
  fov: 'Field of view',
  volume: 'Volume',
  invertY: 'Invert Y axis',
  health: 'HEALTH',
  reload: 'RELOAD',
  noAmmo: 'NO AMMO',
  reloading: 'RELOADING…',
  points: 'Points',
  kills: 'Kills',
  accuracy: 'Accuracy',
  you: 'You',
  kill: 'Kill',
  headshot: 'Headshot',
  longShot: 'Long shot',
  respawnIn: 'Respawning in {s}…',
  debugHint: 'F3 debug · F4 hitboxes',
  keyMove: 'Move',
  keyJump: 'Jump',
  keyCrouch: 'Crouch (while sprinting: slide)',
  keySprint: 'Sprint',
  keyFire: 'Fire',
  keyAds: 'Aim',
  keyReload: 'Reload',
  keyPause: 'Menu',
  mouseLeft: 'Left mouse',
  mouseRight: 'Right mouse',
  keyMelee: 'Knife',
  keyTaunt: 'Humiliate (near a body)',
  keyGrenade: 'Grenade (hold to cook)',
  grenadeName: 'Grenade',
  knife: 'Knifed',
  knifeName: 'Knife',
  dogBite: 'Bite',
  backstab: 'Backstab',
  groin: 'Right in the birdie',
  groinBanner: 'RIGHT IN THE BIRDIE!',
  humiliation: 'Humiliation',
  humiliatedBanner: 'HUMILIATED!',
  danceName: 'Victory Dance',
  promptTaunt: 'Humiliate {name}',
  dancing: 'Humiliating {name}…',
  quality: 'Graphics quality',
  qualityAuto: 'Automatic',
  qualityLow: 'Low',
  qualityMedium: 'Medium',
  qualityHigh: 'High',
  yourName: 'Your name',
  sexLabel: 'Sex',
  sexMale: '♂ Male',
  sexFemale: '♀ Female',
  playOnline: 'PLAY ONLINE',
  playOffline: 'Shooting range (static dummies)',
  playBots: 'VS BOTS',
  botSkill: 'Difficulty',
  botCount: 'Bots',
  skillEasy: 'Easy',
  skillNormal: 'Normal',
  skillHard: 'Hard',
  botsSubtitle: 'Against {n} bots · free-for-all',
  sessions: 'Sessions',
  createSession: 'CREATE',
  sessionNamePlaceholder: 'New session name',
  back: 'Back',
  noSessions: 'No open sessions. Create the first one!',
  join: 'JOIN',
  full: 'FULL',
  joining: 'Joining…',
  connecting: 'Connecting to the server…',
  connectedAs: 'Connected as {name}.',
  disconnected: 'Lost connection to the server.',
  serverOffline: 'Server is down. Run "npm run server" (or play offline training).',
  needName: 'Pick a name first.',
  exitToHome: 'Back to home',
  scoreboard: 'Scoreboard',
  player: 'Player',
  deaths: 'Deaths',
  humiliationsShort: 'Humil.',
  killedBy: '{name} took you out',
  killedByWith: '{name} took you out with {weapon}',
  playerJoined: '{name} joined',
  playerLeft: '{name} left',
  lostConnection: 'No connection to the server',
  onlineSubtitle: 'Session: {name} · free-for-all',
  gpuWarning:
    'Your browser is rendering the game without a graphics card (renderer: {gpu}), which caps it around 10 FPS. Enable “Use graphics acceleration when available” in chrome://settings/system (Edge: edge://settings/system) and restart the browser.',
};

export const TIPS = {
  'pt-BR': [
    'Dica: atirar no inimigo costuma funcionar melhor que atirar na parede.',
    'Dica: o boneco não revida. Ainda.',
    'Dica: cair de 7 metros dói. Pergunte ao seu joelho.',
    'Dica: mirar na cabeça dá o dobro de dano e o triplo de arrogância.',
    'Dica: correr e atirar ao mesmo tempo não é permitido. Sindicato dos braços.',
    'Dica: o caminhão de sorvete não vende sorvete. Mas toca música.',
    'Dica: os flamingos não têm culpa de nada.',
  ],
  en: [
    'Tip: shooting the enemy usually works better than shooting the wall.',
    "Tip: the dummy doesn't shoot back. Yet.",
    'Tip: falling 7 meters hurts. Ask your knees.',
    'Tip: headshots deal double damage and triple arrogance.',
    'Tip: no shooting while sprinting. Arm union rules.',
    "Tip: the ice cream truck doesn't sell ice cream. It does play music.",
    'Tip: the flamingos are innocent.',
  ],
};

export const DEATH_MESSAGES = {
  'pt-BR': {
    fall: ['Você venceu a gravidade. Brincadeira, ela venceu.', 'Da próxima vez, tente cair de pé.', 'A calçada mandou lembranças.'],
    void: ['Você saiu do mapa. O mapa não sentiu sua falta.', 'Explorador corajoso. Explorador morto.'],
    explosion: ['Você cozinhou demais. A granada, e você.', 'Dica: a granada vai na direção do inimigo.'],
    dog: ['A Amora não gostou da visita.', 'Mordido pela Amora. Fofa, mas brava.', 'Quintal errado. Au.'],
  },
  en: {
    fall: ['You beat gravity. Just kidding, it beat you.', 'Next time, try landing on your feet.', 'The sidewalk says hi.'],
    void: ["You left the map. The map didn't miss you.", 'Brave explorer. Dead explorer.'],
    explosion: ['You overcooked it. The grenade, and yourself.', 'Tip: the grenade goes toward the enemy.'],
    dog: ['Amora did not like your visit.', 'Bitten by Amora. Fluffy, but grumpy.', 'Wrong yard. Woof.'],
  },
};

export type Lang = 'pt-BR' | 'en';
export type StringKey = keyof typeof ptBR;

let lang: Lang = navigator.language?.toLowerCase().startsWith('pt') ? 'pt-BR' : 'en';
const dicts: Record<Lang, Record<StringKey, string>> = { 'pt-BR': ptBR, en };

export function getLang(): Lang {
  return lang;
}

export function setLang(l: Lang) {
  lang = l;
}

export function t(key: StringKey, params: Record<string, string | number> = {}): string {
  return dicts[lang][key].replace(/\{(\w+)\}/g, (_, k) => String(params[k] ?? ''));
}

export function pick<T>(list: T[]): T {
  return list[(Math.random() * list.length) | 0];
}
